
excluded: # paths to ignore during linting. Takes precedence over `included`.
  - Carthage
  - Pods
  - fastlane

disabled_rules: # rule identifiers to exclude from running
 - trailing_whitespace
 - identifier_name
